name: water_drink_animation_flutter
description: A Flutter app for animating water drinking progress.

publish_to: 'none' # Remove this line if you plan to publish the package

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  lottie: ^2.0.0
  charts_flutter: ^0.12.0
  audioplayers: ^6.1.0
  provider: ^6.1.2
  cloud_firestore: ^5.6.1
  flutter_local_notifications: ^18.0.1
  flex_color_picker: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/

platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos: